// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using br.ufc.mdcc.hpcshelf.platform.Maintainer;
using br.ufc.mdcc.hpcshelf.platform.maintainer.SAFeHost;


namespace config.example.tc.Application {
    
    
    public interface IApplication<M> : br.ufc.pargo.hpe.kinds.IComputationKind 
		where M:ISAFeHost
		{
    }
}
