// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using br.ufc.mdcc.hpcshelf.mapreduce.connector.JoinLoop;
using br.ufc.pargo.hpe.kinds;
using config.example.sssp.System;
using System;
using System.Threading;


namespace config.example.sssp.impl.SystemImpl {
    
    
    public class IPeer_2Impl : br.ufc.pargo.hpe.kinds.Application, IPeer_2 {
        
        private void Go(Object o) {
            ((Activate)(o)).go();
        }
        
        public override void main() {
          /*  IMapper<br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost.IComputeHost, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.common.String.IString, br.ufc.mdcc.common.String.IString, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.hpcshelf.mapreduce.example.cw.WordCounter.IWordCounter> mapper = ((IMapper<br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost.IComputeHost, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.common.String.IString, br.ufc.mdcc.common.String.IString, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.hpcshelf.mapreduce.example.cw.WordCounter.IWordCounter>)(this.Services.getPort("mapper")));
            Thread go_mapper = new Thread(new ParameterizedThreadStart(this.Go));
            go_mapper.Start(mapper);
            ISplitterMapFeeder<br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost.IComputeHost, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.common.String.IString> splitter = ((ISplitterMapFeeder<br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost.IComputeHost, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.common.String.IString>)(this.Services.getPort("splitter")));
            Thread go_splitter = new Thread(new ParameterizedThreadStart(this.Go));
            go_splitter.Start(splitter);
            IShufflerMapCollector<br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost.IComputeHost, br.ufc.mdcc.common.String.IString, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.hpcshelf.mapreduce.custom.PartitionFunction.IPartitionFunction<br.ufc.mdcc.common.String.IString>> shuffler = ((IShufflerMapCollector<br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost.IComputeHost, br.ufc.mdcc.common.String.IString, br.ufc.mdcc.common.Integer.IInteger, br.ufc.mdcc.hpcshelf.mapreduce.custom.PartitionFunction.IPartitionFunction<br.ufc.mdcc.common.String.IString>>)(this.Services.getPort("shuffler")));
            Thread go_shuffler = new Thread(new ParameterizedThreadStart(this.Go));
            go_shuffler.Start(shuffler);
            go_mapper.Join();
            go_splitter.Join();
            go_shuffler.Join();*/
        }
    }
}
