#!/bin/bash
mv br.ufc.mdcc.common.Data ../SHELF/
mv br.ufc.mdcc.common.impl.IntegerImpl ../SHELF/
mv br.ufc.mdcc.common.impl.IteratorImpl ../SHELF/
mv br.ufc.mdcc.common.impl.KVPairImpl ../SHELF/
mv br.ufc.mdcc.common.impl.NullPlatform ../SHELF/
mv br.ufc.mdcc.common.impl.StringImpl ../SHELF/
mv br.ufc.mdcc.common.Integer ../SHELF/
mv br.ufc.mdcc.common.Iterator ../SHELF/
mv br.ufc.mdcc.common.KVPair ../SHELF/
mv br.ufc.mdcc.common.Platform ../SHELF/
mv br.ufc.mdcc.common.String ../SHELF/
mv br.ufc.mdcc.hpcshelf.gust.binding.environment.BindingDirectMxNIterator ../SHELF/
mv br.ufc.mdcc.hpcshelf.gust.impl.binding.environment.BindingDirectMxNIterator ../SHELF/
mv br.ufc.mdcc.hpcshelf.gust.port.environment.PortTypeIterator ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.impl.ComputePlatform ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.impl.DataPlatform ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.impl.SAFePlatform ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.Maintainer ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.maintainer.ComputeHost ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.maintainer.DataHost ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.maintainer.SAFeHost ../SHELF/
mv br.ufc.mdcc.hpcshelf.platform.Platform ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.channel.Binding ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.channel.impl.BindingImpl ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingBase ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingBaseDirect ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingMbyN ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingMbyNInter ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingMbyNIntra ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentPortType ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentPortTypeMultiplePartner ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentPortTypeSinglePartner ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.task.impl.TaskBindingBaseImpl ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.task.TaskBindingBase ../SHELF/
mv br.ufc.mdcc.hpc.storm.binding.task.TaskPortType ../SHELF/
mv br.ufc.mdcc.hpc.storm.kind.Binding ../SHELF/


