// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using br.ufc.pargo.hpe.kinds;
using mapreduce.Application;
using mapreduce.System;
using mapreduce.Workflow;
using System;
using System.Threading;
using br.ufc.mdcc.hpcshelf.platform.maintainer.SAFeHost;


namespace mapreduce.impl.SystemImpl {
    
    
    public class IRootImpl : br.ufc.pargo.hpe.kinds.Application, IRoot {
        
        private void Go(Object o) {
            ((Activate)(o)).go();
        }
        
        public override void main() {
		/*	IWorkflow<ISAFeHost> workflow = ((IWorkflow<ISAFeHost>)(this.Services.getPort("workflow")));
            Thread go_workflow = new Thread(new ParameterizedThreadStart(this.Go));
            go_workflow.Start(workflow);
			IApplication<ISAFeHost> application = ((IApplication<ISAFeHost>)(this.Services.getPort("application")));
            Thread go_application = new Thread(new ParameterizedThreadStart(this.Go));
            go_application.Start(application);
            go_workflow.Join();
            go_application.Join();*/
        }
    }
}
