// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

//using br.ufc.mdcc.hpcshelf.gust.connector.Join;
//using br.ufc.mdcc.hpcshelf.gust.connector.Step;
using br.ufc.pargo.hpe.kinds;
using config.example.tc3.System;
using System;
using System.Threading;


namespace config.example.tc3.impl.SystemImpl {
    
    
    public class IPeer_3Impl : br.ufc.pargo.hpe.kinds.Application, IPeer_3 {
        
        private void Go(Object o) {
            ((Activate)(o)).go();
        }
        
        public override void main() {
           
        }
    }
}
