// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using br.ufc.mdcc.hpcshelf.platform.Maintainer;
using br.ufc.mdcc.hpcshelf.platform.maintainer.SAFeHost;
using mapreduce.Application;


namespace mapreduce.impl.ApplicationImpl {
    
    
	public class IApplicationImpl<M> : br.ufc.pargo.hpe.kinds.Computation , IApplication<M> 
		where M:ISAFeHost
	{
        
        public override void main() {
        }
    }
}
